name: Rust CI

on:
  commit:
    paths:
      - '**/*.rs'  # Triggered when rust file is updated.

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install rustfmt
      run: cargo install rustfmt

    - name: Check formatting
      run: cargo fmt -- --check

  check-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install cargo fix-check
      run: cargo install cargo-fix-check

    - name: Run cargo fix-check
      run: cargo fix-check --output format=short

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test --all --verbose
