[package]
name = "mpc-trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-std = { path = "../arkworks/std", version = "0.3.0", features = ["std", "print-trace"] }
